name: mypy

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Hatch
        uses: pypa/hatch@install

      - name: Run mypy
        run: hatch run types:check
